# Optimize test profile for faster compilation
[profile.test]
codegen-units = 256

# Optimize dev profile for faster compilation of project code,
# while dependencies are optimized for speed.
[profile.dev]
codegen-units = 256

[profile.dev.package."*"]
opt-level = 3

[doc]
all-features = true
